### ISSUE TITLE
[Feature Request] Fading Armor

### ISSUE THREAD

**Issue by JustAHuman-xD** [enjarai/show-me-your-skin#11]
Allow Armor to Fade Out & In when dealing with the damage timer based change.
Currently when taking damage armor rapidly appears, you could add a fade in
And Vice Versa

**Comment by enjarai** [comment]
This is a good idea, tho I'll probably limit it to a fade out like Luni suggests. I will work on this when I have the time.

**Comment by enjarai** [comment]
Added in 1.2.1, which will be published any second now.

**Comment by JustAHuman-xD** [comment]
It is very nice!
