### ISSUE TITLE
Add Compatibility with PlasmoVoice mod 

### ISSUE THREAD

**Issue by ttrafford7** [enjarai/show-me-your-skin#14]
PlasmoVoice mod adds a mute button to the Social Interactions screen which overlaps the skin configuration button for all users

**Comment by enjarai** [comment]
![image](https://user-images.githubusercontent.com/38552516/174427395-b8cca40c-6fca-45c5-adaa-80c8583e12be.png)

As you can see in the image, there's some slight overlap, but its very much still usable. 

Since it works well enough, I dont think its worth the effort to add extra options for this.
