### ISSUE TITLE
PlasmoVoice compatibility

### ISSUE THREAD

**Issue by ttrafford7** [enjarai/show-me-your-skin#15]
![image_2022-06-18_13-56-04](https://user-images.githubusercontent.com/89706593/174434686-b41c04ae-1e6d-4a04-901a-d5554209a588.png)

**Comment by ttrafford7** [comment]
You haven't tested it right, the microphone overlaps the armor customization button for people who use PlasmoVoice

**Comment by ttrafford7** [comment]
> I cant replicate this issue with the latest version of both mods, what exact versions are you using?

do you play in multiplayer?

**Comment by ttrafford7** [comment]
PV - 1.2.13
SMYS - 1.2.1
1.18.2
![Uploading 1302F607-7B60-453A-9068-0F45F0102CC9.jpeg…]()

**Comment by ttrafford7** [comment]
can send you my .minecraft folder

**Comment by ttrafford7** [comment]
updated PlasmoVoice to 1.2.16
still the same

**Comment by enjarai** [comment]
Ok I've found the issue, it seems like mixins get applied in an arbitrary order, meaning that its completely random which button gets rendered first.

I'll see what the options are for making it compatible.

**Comment by ttrafford7** [comment]
> Ok I've found the issue, it seems like mixins get applied in an arbitrary order, meaning that its completely random which button gets rendered first.
> 
> I'll see what the options are for making it compatible.

I can give you contact of PlasmoVoice developer if you need

**Comment by enjarai** [comment]
Quick update:

I've decided it makes sense to decouple my mod from the overly janky social interactions screen, and I've been working on doing that. Having to rewrite my entire ui is a lot of work, so currently no eta.

**Comment by enjarai** [comment]
Fixed in 1.3.1
