### ISSUE TITLE
Switch button

### ISSUE THREAD

**Issue by ttrafford7** [enjarai/show-me-your-skin#16]
Add key bind to switch between 2 or more custom modes for all players
_example:_
1 mode - all armor is off (0%) and elytra is on (my custom setting number 1)
2 mode - all armor is on (100%) (my custom setting number 2)
3 mode (optional) - 50% of helmet and boots, chestplate and leggings are turned off (0%)
By pressing the bound key, the modes will cycle.

**Comment by enjarai** [comment]
Added global toggle button in 1.3.2.
