### ISSUE TITLE
[Request] Option to Disable Weapon and Tool Enchantment Glint

### ISSUE THREAD

**Issue by ardissaps** [enjarai/show-me-your-skin#17]
Option to Disable Weapon and Tool Glint, the glint make wonderfulness of weapon texture not visible.
![image](https://user-images.githubusercontent.com/82106625/175777855-0bc0858f-f9e9-43dc-94c4-975edd168340.png)

**Comment by enjarai** [comment]
As mentioned in #12, this is outside of the scope of the mod. There are enough other ways to hide enchant glint on items using resource packs.
