### ISSUE TITLE
Feature Request: Show cape instead of elytra

### ISSUE THREAD

**Issue by akoimeexx** [enjarai/show-me-your-skin#18]
I was hoping that if I hid the elytra, the default behavior would be to show my cape instead. Sadly, not the case. Would this be feasible/sensible to add into a future version?

**Comment by enjarai** [comment]
Yes, thats an oversight on my part. I'm currently working on some major changes, so it might be some time until the next update, but I'll make sure to add this.

**Comment by enjarai** [comment]
Fixed in 1.3.2
