### ISSUE TITLE
[Translation] Russian localization

### ISSUE THREAD

**Issue by DearFox** [enjarai/show-me-your-skin#2]
This is an adapted translation into Russian
![image](https://user-images.githubusercontent.com/59219907/167478277-7dc70ab3-5b04-4ceb-b4a7-6083ad93d44e.png)
[ru_ru.zip](https://github.com/enjarai/show-me-your-skin/files/8654548/ru_ru.zip) there is a json file in the archive, unfortunately I can't attach json directly

**Comment by enjarai** [comment]
Works nicely, thanks! I'll add this in the next update.
