### ISSUE TITLE
Crash with MemoryLeakFix

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [enjarai/show-me-your-skin#20]
**MC** 1.19.1
**Fabric API** 0.58.5
**Show Me Your Skin!** 1.2.1
**[MemoryLeakFix](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)** 0.6.0

Initially reported to MLF, but the author said the issue should be fixed on your side: https://github.com/fxmorin/MemoryLeakFix/issues/35#issuecomment-1198385082

Logs: https://gist.github.com/Footage2-Amply-Pounce/ab38219c8784e97d7f71c74b057b0295

**Comment by enjarai** [comment]
At a quick glance, this seems to be a change in 1.19.1 that broke one of my mixins related to the social interactions screen, which makes sense.

I'm currently working on rewriting the config menu to move it away from the social interactions screen, so I wont bother fixing this right now.

I'll leave this issue open until my update is actually working though.

**Comment by Footage2-Amply-Pounce** [comment]
Oh, yep, just discovered that even just opening the social interactions screen crashes the game. Will be waiting for an update :)

**Comment by enjarai** [comment]
Fixed in 1.3.1
