### ISSUE TITLE
Fabric ArmorRenderer always displaying armor, despite settings

### ISSUE THREAD

**Issue by Noaaan** [enjarai/show-me-your-skin#23]
Probably similar to First Person Models issue: https://github.com/tr7zw/FirstPersonModel/issues/227

They solved it recently by injecting before FAPI, since their ArmorRenderer likes to override anything else. 
https://github.com/tr7zw/FirstPersonModel/commit/54608f8b781bc12cce4af309cef1cf049fe1908c

![image](https://user-images.githubusercontent.com/4163353/183290906-fe386e81-7d51-471e-8daf-88a65cbc6c4c.png)

**Comment by enjarai** [comment]
I was told about this issue via discord earlier today, so I've actually already fixed it in the latest commit using a similar method to what you mention and a mixin into FAPI. If you'd made this issue two hours earlier it might've saved me a bit of searching 😅. no worries though.

I'll backport these changes to 1.18.2, and push a release after that. Expect to see it within the hour.
