### ISSUE TITLE
[Feature Request]  Hiding Enchantment Glint unless hurt

### ISSUE THREAD

**Issue by MLMII** [enjarai/show-me-your-skin#26]
Show Enchantment Glow when hurt (basically the same as the armor setting) this would allow people to simulate a magical aura protecting them in combat but not active at all times.

Thank you for your time

**Comment by enjarai** [comment]
This would be an interesting feature for sure, but because of how the ui is structured right now, it'd be difficult to implement in an intuitive way.

I probably wont add this.
