### ISSUE TITLE
1.19.3 label

### ISSUE THREAD

**Issue by Aces-and-Jacks** [enjarai/show-me-your-skin#29]
you forgot to put the 1.19.3 label

**Comment by enjarai** [comment]
where do you mean exactly?

**Comment by Aces-and-Jacks** [comment]
<img width="966" alt="Screen Shot 2022-12-04 at 6 33 42 PM" src="https://user-images.githubusercontent.com/106651342/207009346-b45a0d71-b627-4580-bd74-ee072c5a2cfc.png">

**Comment by Aces-and-Jacks** [comment]
<img width="828" alt="SCR-20221212-64o" src="https://user-images.githubusercontent.com/106651342/207009453-85fbfe1d-e4e2-4490-aca7-91f53ab86942.png">

**Comment by Aces-and-Jacks** [comment]
or at least the client launcher i use isn't picking it up as a 1.19.3 mod

**Comment by Aces-and-Jacks** [comment]
ok then. thanks

**Comment by enjarai** [comment]
It seems to have worked, there should be a seperate 1.19.3 version available now.
