### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by audimatic** [enjarai/show-me-your-skin#31]
[crash-2023-01-09_19.51.22-client.txt](https://github.com/enjarai/show-me-your-skin/files/10375253/crash-2023-01-09_19.51.22-client.txt)

**Comment by Zzombiee2361** [comment]
I experienced the same thing, what did you do?

**Comment by enjarai** [comment]
Seems like an issue with a mod named "nmuk".

**Comment by Zzombiee2361** [comment]
I'm sure it's caused by this mod. First time the game ran fine, then when finished setting the mod, I go back and the game crashed. Then the game just won't launch with this mod.

I tried deleting the config file and it worked
