### ISSUE TITLE
Legs rendering issue.

### ISSUE THREAD

**Issue by foureyesfries** [enjarai/show-me-your-skin#33]
I've been having some issues specifically with rendering legs.

when changing the opacity of leg armor, legs aren't rendered, and you can basically see through them. Since leg armor also goes higher than the player's legs, into the torso that is, it basically removes that part of the torso as well.

any possible fixes?

**Comment by enjarai** [comment]
This is a known compatibility issue with Iris (#19). It'll do that even when you have no shaders loaded. 

Currently the only fix is to uninstall Iris completely.
