### ISSUE TITLE
Problem OptiFine

### ISSUE THREAD

**Issue by MrNocis** [enjarai/show-me-your-skin#34]
I noticed that when I have the OptiFine mod installed, Show Me Your Skin crashes. Can this be resolved?

**Comment by Kikugie** [comment]
Optifine has many incompatibilities and isn't supported. Please consider alternatives https://lambdaurora.dev/optifine_alternatives/

**Comment by enjarai** [comment]
To add to that, I'd support Optifine if I could, but it's closed source and invasive nature makes it basically impossible for me to do so.

All Optifine features have been ported as fabric mods at this point though, so there's really no reason to use it anymore.
