### ISSUE TITLE
[BUG]: Can't open config with Essential Mod installed

### ISSUE THREAD

**Issue by Kaden-Skinner** [enjarai/show-me-your-skin#39]
https://mclo.gs/XOktYgK

Load Minecraft with Essential Mod and Show Me Your Skin and Mod Menu
Get any cosmetic from Essential Mod
Click Mods
Try to edit the config of Show Me Your Skin
Game crashes.

**Comment by enjarai** [comment]
This seems to be an issue with Essential that I can't really do much about on my end. It's wrongly assuming you to be logged into a world when it tries to render cosmetics, which is not always the case. 

The config screen should work fine when you *are* logged into a world, but an actual fix will have to come from Essential. It should be a one-line change on their side.

**Comment by DJtheRedstoner** [comment]
Hi, Essential dev here. We've fixed this in 1.2.1: https://essential.gg/changelog. Just (re)start your game to receive the update.
