### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HeatwaveDaGreat** [enjarai/show-me-your-skin#4]
When opening the customization menu in mod menu it crashes for some reason

[crash-2022-05-10_14.56.21-client.txt](https://github.com/enjarai/show-me-your-skin/files/8692164/crash-2022-05-10_14.56.21-client.txt)

**Comment by enjarai** [comment]
This is an incompatibility with the 3D Skin Layers mod, and I can't fix this on my side. I will open an issue on their github.

For now you can remove either mod and it should work.

**Comment by HeatwaveDaGreat** [comment]
Ok thanks for the information. Would really appreciate it if you put a warning on the mod page so other don't make the same mistake
