### ISSUE TITLE
Sadly a dealbreaker

### ISSUE THREAD

**Issue by notIkibo** [enjarai/show-me-your-skin#40]
Heya dev,

your mod is so cool ngl, but apparently your mod needs compat with every mod that has their own selection of armor.

I've noticed that BetterEnd compat does exist while "Immersive Armor", "DragonLoot", "Deeper&Darker", "BetterAnimalPlus" and "Marium's Soulslike Weaponry" don't. I'm sure its fairly annoying when players say they want compat for this mod. 
For me, it's quite sad that compat has to be manually achieved. I don't know a lot about coding though apparently it wasn't possible to ensure compat maybe through tags? That any armor that has a specific tag is included. Considering that BetterEnd equipment has no tags innit yet still has compat, I reckon that it doesn't work with tags.

So now: You have a great mod, damn I love the functionality. Especially since just having enchantment glint just looks way too flashy for my taste. But getting compat for every mod in the world surely is a hassle. If I had a modpack that doesn't have so many different mod armors, I'd use it for sure, but I guess I wouldn't wanna ask for compat just for my case.

If you think otherwise and are convinced that the mods mentioned are popular enough for you to work on compat and do make an update for it. Hmu bruv, this is solid

**Comment by Benonardo** [comment]
This mod should work with all mods using the vanilla or Fabric API armor rendering techniques (see the screenshot below).
![image](https://github.com/enjarai/show-me-your-skin/assets/75318636/c5afe04f-62bd-4fd8-9921-3fd12a17883d)

**Comment by notIkibo** [comment]
Damn, I understand. That's insane, especially when it comes to compatibility. Thank you for that message.

**Comment by enjarai** [comment]
Yea, it'll be hard to make compat for any mod that doesn't use standard Fabric API tools to render their armor.
