### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Katbruh** [enjarai/show-me-your-skin#41]
i tried to load with only 2 mods "fabric-api-0.76.1+1.19.3" and "show-me-your-skin-1.3.7+1.19.3" but it crashes everytime i join the game using TLauncher
here's the log:
[latest.log](https://github.com/enjarai/show-me-your-skin/files/11581869/latest.log)

**Comment by Katbruh** [comment]
and here's the crash report
[crash-2023-05-27_19.22.09-client.txt](https://github.com/enjarai/show-me-your-skin/files/11581881/crash-2023-05-27_19.22.09-client.txt)

**Comment by Katbruh** [comment]
please help

**Comment by enjarai** [comment]
Pirated launchers are not supported, please buy the game and use a proper launcher if possible.

**Comment by Katbruh** [comment]
somehow after you replied its working again, tysm
