### ISSUE TITLE
1.20 respawn

### ISSUE THREAD

**Issue by maky54321** [enjarai/show-me-your-skin#42]
on 1.20 theres an issue where if u die u cannot respawn anymore for some reason

**Comment by enjarai** [comment]
I've found the cause of the issue, but its a problem with Cardinal Components, an API I use. Since I don't have control over that API, I can't fix the problem until an update comes from them.

For now, I'll take down the 1.20 versions of Show Me Your Skin, as this is quite a critical issue.

**Comment by enjarai** [comment]
Forgot about this issue report, but the issue was fixed a while ago. A 1.20 and 1.20.1 version is up.
