### ISSUE TITLE
Not an issue, but what?

### ISSUE THREAD

**Issue by Random-MCreator-Dev** [enjarai/show-me-your-skin#46]
Found this in the log:

11:39:27.588
[cicada] Don't you miss the times when mods would converse with each other in the game log?
11:39:27.589
[showmeyourskin] Hmm, I don't know. It always seemed a little cringey to me.

**Comment by Benonardo** [comment]
That's by https://github.com/enjarai/cicada-lib, enjarai's mods just kind of talk to each other sometimes using that.

**Comment by enjarai** [comment]
Indeed.
