### ISSUE TITLE
armor opacity not working on servers

### ISSUE THREAD

**Issue by gamerroo** [enjarai/show-me-your-skin#49]
Im not sure if its supposed to not work or not but i cant get it to work when on a server

**Comment by gamerroo** [comment]
it worked fine in singleplayer but it doesnt work in the slightest in multiplayer

**Comment by gamerroo** [comment]
it makes the opacity 97% even if my opacity is at 1% or 0%

**Comment by enjarai** [comment]
I don't quite understand what the issue is, does the global configuration not work? Does the server have the mod installed as well? It'll behave differently if thats the case.

**Comment by gamerroo** [comment]
im sorry about taking ages to respond, i was doing something.
the server doesnt have the mod installed but since the transparency was client sided i thought it would basically be the same
and yes it is the global config not working

**Comment by enjarai** [comment]
It should work without being installed on the server yes, though only for you. Make sure you dont have any player-specific overrides left enabled by accident.

**Comment by enjarai** [comment]
Assuming this to be solved due to inactivity.
