### ISSUE TITLE
Incompatibility with ImmediatelyFast

### ISSUE THREAD

**Issue by ImGRUI** [enjarai/show-me-your-skin#50]
When using ImmediatelyFast with Show Me Your Skin, armor trims dissapears when any of armor opacity changed to 0. Logs (Empty): https://mclo.gs/HRxtZRC . Tested with only Fabric API, Show Me Your Skin and ImmediatelyFast. Video:

https://github.com/enjarai/show-me-your-skin/assets/91282421/db340785-c0b6-4ad8-be85-f7f8529e9486

ImmediatelyFast config is default.

**Comment by enjarai** [comment]
It seems like ImmediatelyFast changes the rendering order of trims to prevent unnessecary texture switching, thus reducing frame times ever so slightly. I'll probably be able to implement a workaround though, I'll look into it.
