### ISSUE TITLE
incompatibility with Wildfire Gender Mod

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [enjarai/show-me-your-skin#51]

**Comment by enjarai** [comment]
I'm going to need a little more information. What exactly doesn't work when using the two mods together? What version of either mod are you using?

**Comment by MIPOHBOPOHIH** [comment]
> I'm going to need a little more information. What exactly doesn't work when using the two mods together? What version of either mod are you using?

If you log into the server/enter the wildfire gender mod config via the mod menu, the game will crash. 
https://mclo.gs/s7v1vqy

versions:
Wildfire Gender Mod: 3.0.1
Show Me Your Skin: 1.6.7
Fabric API: 0.86.0

https://github.com/enjarai/show-me-your-skin/assets/98014624/6f466fb7-e1e9-42d6-870b-6c6882b264e1

**Comment by enjarai** [comment]
Fixed in 1.6.8.
