### ISSUE TITLE
Game crashed when open configuration in the mod menu from the title screen

### ISSUE THREAD

**Issue by MaoYan5985** [enjarai/show-me-your-skin#56]
Game crashed when open configuration in the mod menu from the title screen
Here are the steps:

1. Press mod in title screen
![1](https://github.com/enjarai/show-me-your-skin/assets/122714639/9a68e231-07dd-4455-88d4-de674ce6c88d)

2. Open configuration
![2](https://github.com/enjarai/show-me-your-skin/assets/122714639/e2d82cdb-d1b3-4366-8baa-a155009071d8)

3. Game crashed
![3](https://github.com/enjarai/show-me-your-skin/assets/122714639/26f67a8d-42f5-4ffd-9ebe-e3ce650b0f5a)

Show me your skin! works fine in singleplayer/multiplayer, but trying to open configuration in title screen will cause game crash.
[crash-reports.log](https://mclo.gs/QRXcDwj)

- MC : 1.20.1
- Fabric : 0.14.22
- show-me-your-skin-1.6.10+1.20
- modmenu-7.2.1

**Comment by enjarai** [comment]
This seems to be an incompatibility with Neat by Vazkii. A fix will have to come from their side.

From a technical perspective: Neat assumes that `client.player` will never be null if an entity is being rendered, which is not true in this case.
