### ISSUE TITLE
Server thread hang

### ISSUE THREAD

**Issue by jarezzz** [enjarai/show-me-your-skin#59]
Mod prevents server from stopping properly, probably hanging some threads, when I remove it it is fine.
![image](https://github.com/enjarai/show-me-your-skin/assets/8466043/9fec7c4c-7ed3-40f0-b893-2977e36e1619)
It stays like this forever

**Comment by jacg311** [comment]
Looks like a duplicate of #38

**Comment by jarezzz** [comment]
yeah, my bad, haven't searched properly
