### ISSUE TITLE
Does not work on Modded Armor

### ISSUE THREAD

**Issue by ardissaps** [enjarai/show-me-your-skin#6]
Transparency does not work on modded armor but hide enchantment works fine.

Edit : 
+ Hide enchantmen also does not work on modded armors.
+ Does not hide elytra on trinket mod slot.

**Comment by enjarai** [comment]
What modded armor specifically does it not work with?

**Comment by ardissaps** [comment]
> What modded armor specifically does it not work with?
 
Immersive Armor :
https://github.com/enjarai/show-me-your-skin/issues/6#issuecomment-1140183786

Elytra Trinker (unable to hide) :
https://www.curseforge.com/minecraft/mc-mods/elytra-trinket-fabric

**Comment by enjarai** [comment]
At a glance I can tell that Immersive Armor uses a highly custom armor renderer for it's 3d shapes. So it's not surprising to me that it doesn't work out of the box. 

Looking more closely into its source code, I think it's not worth my time to add support for it. I am however open to merging a pull request for this.

Elytra Trinket has a similar problem, in that it basically copies the vanilla elytra rendering code, bypassing my modifications. This does seem like it'd be easy to support with an optional mixin though, so I'll see what I can do about it.

**Comment by enjarai** [comment]
I got Elytra Trinket working, compatibility will be included in the next update.

**Comment by ardissaps** [comment]
> I got Elytra Trinket working, compatibility will be included in the next update.

Thank you! :)
