### ISSUE TITLE
Game crashes when changing settings while not in a world.

### ISSUE THREAD

**Issue by amyfromearth** [enjarai/show-me-your-skin#61]
Using ModMenu open settings and choose your character then clicking on elytra tab game hangs for a moment and then crashes.

[crash-2023-10-05_23.10.27-client.txt](https://github.com/enjarai/show-me-your-skin/files/12827655/crash-2023-10-05_23.10.27-client.txt)

**Comment by enjarai** [comment]
Seems like Elytra Trims is assuming `client.player` to not be null when a player is rendered. My mod relies on other mods not assuming this. This has to be fixed on their side.

**Comment by kikugie** [comment]
Counterargument: you have Elytra Trims 1.3.3. This doesn't occur on the latest version.
