### ISSUE TITLE
Incompatible with Wildfire's Gender Mod

### ISSUE THREAD

**Issue by error0rre** [enjarai/show-me-your-skin#62]
Transparency is applied not only to the armor, which is why the chest disappears (with full transparency it is not there at all even if the armor is not worn) as in the screenshot:
![2023-10-14_12 08 55](https://github.com/enjarai/show-me-your-skin/assets/128624714/bfe59c64-54cd-4657-bd83-47547cdb41f0)

**Comment by enjarai** [comment]
See #63 for tracking compatibility with WFGM. This specific problem could also be related to Iris.
