### ISSUE TITLE
Wildfire's Female Gender Mod - Crash 1.20.2 (Mixin Related)

### ISSUE THREAD

**Issue by WildfireRomeo** [enjarai/show-me-your-skin#63]
Show Me Your Skin **1.7.0**
Wildfire's Female Gender Mod **3.2.1**
Minecraft Version **1.20.2**

Armor rendering has changed in my mod's latest version, causing your Mixin to fail and crash the game. It was separated to it's own `GenderArmorLayer.java` class to allow rendering on more than just `PlayerEntity` models (i.e. armor stands now).

WildfireRomeo/WildfireFemaleGenderMod#163

This is most likely the new method you want to Mixin.
`protected void renderBreastArmor(T entity, MatrixStack matrixStack, VertexConsumerProvider vertexConsumerProvider, int packedLightIn, boolean left) {
...
}
`

**Comment by enjarai** [comment]
Ah, thanks for letting me know. I'll push an update soon. Is this only changed post-1.20.2, or is 1.20.1 or lower affected as well?

**Comment by enjarai** [comment]
I've disabled the compat module for now, to at least prevent a crash. The code I'm targetting seems to have changed significantly, so I'll have to reconsider how I'll approach compat.

**Comment by PeglinX** [comment]
The crash is only on 1.20.2 not 1.20.1

**Comment by enjarai** [comment]
Fixed as of 1.9.0.
