### ISSUE TITLE
Causes invincibility until re-enabled 1.20.1 Fabric

### ISSUE THREAD

**Issue by twenty41** [enjarai/show-me-your-skin#67]
When you have your own skin opacities set to zero, you will sometimes turn invincible until you disable and re-enable.

**Comment by enjarai** [comment]
Do you mean invincible or invisible? Those are very different.

**Comment by twenty41** [comment]
Invincible. Sorry, closing this

 It was actually a login protection mod causing the problem but for some reason disabling and re-enabling your mod would fix it temporarily
