### ISSUE TITLE
[SMYS 1.7.1] Game boots, but Mojang loading screen never fades out.

### ISSUE THREAD

**Issue by ChiesyCake** [enjarai/show-me-your-skin#69]
**Show Me Your Skin:** 1.7.1
**Minecraft:** 1.20.4
**Fabric Loader:** 0.15.6

**Issue:**
Minecraft will successful load in, but the Mojang loading screen will stay stuck on screen and not fade away. The game is not frozen, background music will play and you can hear options being selected when you click on the screen. It seems to be a conflict with Wildfire's Female Gender mod, since booting the game without it loads fine, and booting the game with WFG mod but without SMYS loads fine.

**Cause:**
Conflict with Wildfire's Female Gender Mod (1.20.2-3.2.1)

**Mod List:**
\- appleskin 2.5.1+mc1.20.3
\- capes 1.5.3+1.20.2
\- continuity 3.0.0-beta.4+1.20.2
\- fabric-api 0.91.3+1.20.4
\- fabric-language-kotlin 1.10.17+kotlin.1.9.22
\- fabricloader 0.15.6
\- ferritecore 6.0.3
\- immediatelyfast 1.2.8+1.20.4
\- iris 1.6.14
\- litematica 0.17.0
\- lithium 0.12.1
\- malilib 0.18.0
\- midnightcontrols 1.9.2+1.20.4
\- midnightlib 1.5.3
\- modmenu 9.0.0
\- notenoughanimations 1.7.0
\- raised 3.1.1
\- reeses-sodium-options 1.7.0+mc1.20.2-build.97
\- showmeyourskin 1.7.1+1.20.4
\- shulkerboxtooltip 4.0.8+1.20.4
\- sodium 0.5.5
\- sodium-extra 0.5.3+mc1.20.2-build.114
\- wildfire_gender 1.20.2-3.2.1
\- xaerominimap 23.9.7
\- xaeroworldmap 1.37.7

**Comment by enjarai** [comment]
This is a known issue, see #63.
