### ISSUE TITLE
incompatibility with bobby?

### ISSUE THREAD

**Issue by 0DamI0** [enjarai/show-me-your-skin#7]
https://pastebin.com/2fddh525

**Comment by enjarai** [comment]
(Edited to put the crashlog in a pastebin)

At a glance it looks like Bobby doesn't like that the mod creates a dummy world to render the player character in UIs. I'm not sure how easy this will be to fix, but I'll look into it.

**Comment by enjarai** [comment]
Fixed in 1.1.1.
