### ISSUE TITLE
Opacity does not apply on head items. (player heads, commonly used in Hypixel Skyblock)

### ISSUE THREAD

**Issue by Lopzinc** [enjarai/show-me-your-skin#71]
Head items will stay 100% opacity no matter what.
![image](https://github.com/enjarai/show-me-your-skin/assets/61240663/8804a8e4-a984-4264-a18e-fcb84fdbe7e2)
![image](https://github.com/enjarai/show-me-your-skin/assets/61240663/9b0b9990-5ba6-46c4-af1e-852538609af4)

**Comment by enjarai** [comment]
Added an additional slider to configure "hat" transparency in mod version 1.8.0.

**Comment by Lopzinc** [comment]
Thank you!
