### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by Bipbip2109** [enjarai/show-me-your-skin#72]
![Scan1](https://github.com/enjarai/show-me-your-skin/assets/88253359/5b3a1fbf-5fc6-4aaf-868e-aa2846e29307)

While launching the game with the latest windows 11 insider preview, this mod and clientcommands were both flagged as containing the trojan "Trojan:Script/Wacatac.B!ml", probably a false positive but we never know

A similar issue was posted by myself on https://github.com/Earthcomputer/clientcommands

**Comment by kikugie** [comment]
Microsoft defender is just stupid and sometimes does that to java files. It's not a trojan as verified by curseforge and modrinth, and even by yourself reading the source code right here if you want.

**Comment by enjarai** [comment]
Yes, if you downloaded the mod from either Curseforge or Modrinth, they basically guarantee it to be safe. This is most likely a false positive from your viris scanner, which does happen sometimes.
