### ISSUE TITLE
[Feature] 1.20.5/6 support

### ISSUE THREAD

**Issue by sylvxa** [enjarai/show-me-your-skin#76]
1.20.5 released recently and [1.20.6 is scheduled for early next week, with minimal changes](https://www.minecraft.net/en-us/article/minecraft-1-20-6-release-candidate-1). There were a decent number of changes under the hood, including but not limited to:

- Java version being bumped to 21 (and with that Gradle and Loom must be updated I believe?)
- Networking changes (The Fabric Networking API has switched to `PacketCodec`s)

**Comment by enjarai** [comment]
A port is definitely planned, but I'm going to wait for any additional minor updates mojang decides to release. This mod will probably require a large effort to port due to all the under the hood changes, so keep in mind it might take some more time than past updates.

**Comment by enjarai** [comment]
Ah I forgot to close this after I updated. I've released 1.10.0 with 1.20.5-6 support.
