### ISSUE TITLE
Vanilla players are unable to join the server due to CCA sync requirement

### ISSUE THREAD

**Issue by zawe** [enjarai/show-me-your-skin#80]
Hello,
CCA is now enforcing this mod to be installed on all clients. Vanilla players are unable to join due to https://ladysnake.org/wiki/cardinal-components-api/upgrade-instructions/CCA-6-changes#client-optional-components

Here is an example of what happens(with a different mod, but the error message is the same) with a solution to enable vanilla clients to join again.
https://github.com/Ladysnake/Cardinal-Components-API/issues/174

Thank you

**Comment by enjarai** [comment]
Ah, lovely, I completely missed that they changed that. I'll find a workaround soon™.

**Comment by zawe** [comment]
Thank you.
My friends and I really like this mod, thank you for developing it and sharing it with all of us. ❤️

**Comment by enjarai** [comment]
Should be fixed as of version 1.10.2 of the mod, let me know if there are any more issues.
