### ISSUE TITLE
Wearing a set of armor with the same material makes players legs invisible when armor is partially transparent

### ISSUE THREAD

**Issue by TheBlazewing** [enjarai/show-me-your-skin#86]
Doesn't need to be a full set, happens when at least wearing chest and legs, with either equipping helmet or boots causing the legs of the players skin to be invisible. Doesn't happen when mixing armor types

![2024-07-02_03 22 50](https://github.com/enjarai/show-me-your-skin/assets/174425156/dc86e24e-eeec-4063-a2cc-fcfc54848ada)

**Comment by enjarai** [comment]
This is part of a known bug with Iris. See #19.
