### ISSUE TITLE
Crystalite Armour from BetterEnd does not hide with SMYS

### ISSUE THREAD

**Issue by VixenGames** [enjarai/show-me-your-skin#87]
Hello!
So I'm in a server and we have show me your skin and both the Better End and Better Nether mods,

Within those mods,
BetterNether armour works, and in BetterEnd all the armour except for Crystallite works

Crystallite shows up no matter what. I'm not sure if this has to do with the fact it always is giving the player alternate effects like haste, speed and extra health? But we wanted to submit a ticket to hopefully see a fix? 

Cheers. Images below. 
![image](https://github.com/enjarai/show-me-your-skin/assets/156526915/ab8574df-1751-4da9-bef6-b633bc4cdb3c) Wearing Crystallite

![image](https://github.com/enjarai/show-me-your-skin/assets/156526915/0a04cca3-e60a-46b2-bba2-fac3ba8f2053)
Wearing any other armour (diamond, etc)

**Comment by enjarai** [comment]
The armor might be using a custom renderer without going through Fabric Rendering API properly. I cannot control the transparency for the armor of mods that do this. A fix would have to come from Better End.
