### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'showmeyourskin'!

### ISSUE THREAD

**Issue by Marotheit** [enjarai/show-me-your-skin#88]
Show Me Your Skin causes the game to be unable to load on Minecraft 1.21.

GitHub Gist of the Crashlog: https://gist.github.com/Marotheit/e81941621d4cb8ab0a1aaa673a216924

**Comment by StellarWitch7** [comment]
I think seeing your SMYS config file might be beneficial. It should be under `config/` in your Minecraft instance's directory, as `showmeyourskin.json`. Your launcher should provide a button to open the instance's directory. (Crash log says you're using `theseus`, which I believe is the Modrinth Launcher?)

### What is the error?
From what I can tell, your config file is broken, and therefore cannot be loaded. Deleting it may fix the issue. A couple causes of this issue may be either the file was edited outside of the mod's config menu, or SMYS failed to save it properly. If you edit the config file in a text editor, take care to maintain the format and structure. 

I hope this helps! 

**Note**: I am not a contributor and have little to no knowledge regarding how SMYS works, this is just what I have gathered from the crash log.

**Comment by Marotheit** [comment]
Sorry for the late reply, here is my config file:

https://gist.github.com/Marotheit/491944797b3142a5ceba7887010acdca

**Comment by StellarWitch7** [comment]
@enjarai looks to be there's an extra comma at the end of the config. It says it expects a name. 

@Marotheit try removing the last comma in the config.

**Comment by Marotheit** [comment]
> @enjarai looks to be there's an extra comma at the end of the config. It says it expects a name.
> 
> @Marotheit try removing the last comma in the config.

That worked! I'm not really sure how this happened, I don't remember editing the configuration file at all (although I'm no stranger to doing so from time-to-time), I just updated the mod to 1.21. Thanks for your help.

**Comment by StellarWitch7** [comment]
No problem. The update likely had some change in the parser that caused it to fail with the old config.
