### ISSUE TITLE
Version 1.11.3 on Modrinth does not list 1.21.1 as a supported version

### ISSUE THREAD

**Issue by Tisawesomeness** [enjarai/show-me-your-skin#95]
See https://modrinth.com/mod/show-me-your-skin/version/1.11.3+1.21

**Comment by SussyBob** [comment]
Because it's simply doesn't support 1.21.1 i think, i've tried it.

**Comment by enjarai** [comment]
It should definitely support 1.21.1, it seems I made a mistake uploading it. Fixed now.
